apiRules:
- include:
    uidRegex: ^Klem\.SocketChat\.ChatSystem
    type: Namespace
- include:
    uidRegex: ^Klem\.SocketChat\.ChatSystem\.Interfaces
    type: Interface
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: ^Klem\.SocketChat\.ChatSystem\.SimpleChatSample
    type: Namespace
- exclude:
    uidRegex: ^Klem\.SocketChat\.Tests
    type: Namespace
- exclude:
    uidRegex: .* # Every other namespaces are ignored
    type: Namespace